onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /pixel_fetcher_tb/dut/clk_i
add wave -noupdate /pixel_fetcher_tb/dut/rst_ni
add wave -noupdate /pixel_fetcher_tb/dut/req_o
add wave -noupdate /pixel_fetcher_tb/dut/rsp_i
add wave -noupdate /pixel_fetcher_tb/dut/r_o
add wave -noupdate /pixel_fetcher_tb/dut/g_o
add wave -noupdate /pixel_fetcher_tb/dut/b_o
add wave -noupdate /pixel_fetcher_tb/dut/enable_i
add wave -noupdate /pixel_fetcher_tb/dut/next_frame_id_i
add wave -noupdate /pixel_fetcher_tb/dut/cx_o
add wave -noupdate /pixel_fetcher_tb/dut/cy_o
add wave -noupdate /pixel_fetcher_tb/dut/valid_o
add wave -noupdate /pixel_fetcher_tb/dut/consume_i
add wave -noupdate /pixel_fetcher_tb/dut/block_valid_q
add wave -noupdate /pixel_fetcher_tb/dut/rptr
add wave -noupdate /pixel_fetcher_tb/dut/rptr_block
add wave -noupdate /pixel_fetcher_tb/dut/wptr
add wave -noupdate /pixel_fetcher_tb/dut/response_block
add wave -noupdate /pixel_fetcher_tb/dut/free_size
add wave -noupdate /pixel_fetcher_tb/dut/pixel_r_q
add wave -noupdate /pixel_fetcher_tb/dut/pixel_g_q
add wave -noupdate /pixel_fetcher_tb/dut/pixel_b_q
add wave -noupdate /pixel_fetcher_tb/dut/pixel_cx_q
add wave -noupdate /pixel_fetcher_tb/dut/pixel_cy_q
add wave -noupdate /pixel_fetcher_tb/dut/pixel_valid_q
add wave -noupdate /pixel_fetcher_tb/dut/source_valid
add wave -noupdate /pixel_fetcher_tb/dut/pixel_ready
add wave -noupdate /pixel_fetcher_tb/dut/load_pixel
add wave -noupdate /pixel_fetcher_tb/dut/fetch_cx
add wave -noupdate /pixel_fetcher_tb/dut/fetch_cy
add wave -noupdate /pixel_fetcher_tb/dut/cur_frame_id
add wave -noupdate /pixel_fetcher_tb/dut/state_q
add wave -noupdate -divider {tb top}
add wave -noupdate /pixel_fetcher_tb/clk
add wave -noupdate /pixel_fetcher_tb/rst_n
add wave -noupdate /pixel_fetcher_tb/req
add wave -noupdate /pixel_fetcher_tb/rsp
add wave -noupdate /pixel_fetcher_tb/r
add wave -noupdate /pixel_fetcher_tb/g
add wave -noupdate /pixel_fetcher_tb/b
add wave -noupdate /pixel_fetcher_tb/enable
add wave -noupdate /pixel_fetcher_tb/next_frame_id
add wave -noupdate /pixel_fetcher_tb/cx
add wave -noupdate /pixel_fetcher_tb/cy
add wave -noupdate /pixel_fetcher_tb/valid
add wave -noupdate /pixel_fetcher_tb/consume
add wave -noupdate /pixel_fetcher_tb/errcnt
add wave -noupdate /pixel_fetcher_tb/mem_stall_en
add wave -noupdate /pixel_fetcher_tb/mem_ready_q
add wave -noupdate /pixel_fetcher_tb/consumer_stall_en
add wave -noupdate /pixel_fetcher_tb/consumer_ready_q
add wave -noupdate /pixel_fetcher_tb/exp_cx
add wave -noupdate /pixel_fetcher_tb/exp_cy
add wave -noupdate /pixel_fetcher_tb/exp_frame_id
add wave -noupdate /pixel_fetcher_tb/prev_valid
add wave -noupdate /pixel_fetcher_tb/prev_consume
add wave -noupdate /pixel_fetcher_tb/prev_r
add wave -noupdate /pixel_fetcher_tb/prev_g
add wave -noupdate /pixel_fetcher_tb/prev_b
add wave -noupdate /pixel_fetcher_tb/prev_cx
add wave -noupdate /pixel_fetcher_tb/prev_cy
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {2018657 fs} 0}
quietly wave cursor active 1
configure wave -namecolwidth 219
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {2008621 fs} {2069183 fs}
