onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /rasterizer_tb/DUT/clk_i
add wave -noupdate /rasterizer_tb/DUT/rst_ni
add wave -noupdate /rasterizer_tb/DUT/ab_topleft_i
add wave -noupdate /rasterizer_tb/DUT/bc_topleft_i
add wave -noupdate /rasterizer_tb/DUT/ca_topleft_i
add wave -noupdate /rasterizer_tb/DUT/un_topleft_i
add wave -noupdate /rasterizer_tb/DUT/vn_topleft_i
add wave -noupdate /rasterizer_tb/DUT/iw_topleft_i
add wave -noupdate /rasterizer_tb/DUT/ab_dx_i
add wave -noupdate /rasterizer_tb/DUT/ab_dy_i
add wave -noupdate /rasterizer_tb/DUT/bc_dx_i
add wave -noupdate /rasterizer_tb/DUT/bc_dy_i
add wave -noupdate /rasterizer_tb/DUT/ca_dx_i
add wave -noupdate /rasterizer_tb/DUT/ca_dy_i
add wave -noupdate /rasterizer_tb/DUT/un_dx_i
add wave -noupdate /rasterizer_tb/DUT/un_dy_i
add wave -noupdate /rasterizer_tb/DUT/vn_dx_i
add wave -noupdate /rasterizer_tb/DUT/vn_dy_i
add wave -noupdate /rasterizer_tb/DUT/iw_dx_i
add wave -noupdate /rasterizer_tb/DUT/iw_dy_i
add wave -noupdate /rasterizer_tb/DUT/min_x_i
add wave -noupdate /rasterizer_tb/DUT/min_y_i
add wave -noupdate /rasterizer_tb/DUT/max_x_i
add wave -noupdate /rasterizer_tb/DUT/max_y_i
add wave -noupdate /rasterizer_tb/DUT/start_i
add wave -noupdate /rasterizer_tb/DUT/idle_o
add wave -noupdate /rasterizer_tb/DUT/seg_x_q
add wave -noupdate /rasterizer_tb/DUT/seg_x_d
add wave -noupdate /rasterizer_tb/DUT/seg_x_min
add wave -noupdate /rasterizer_tb/DUT/seg_x_max
add wave -noupdate /rasterizer_tb/DUT/seg_y_q
add wave -noupdate /rasterizer_tb/DUT/seg_y_d
add wave -noupdate /rasterizer_tb/DUT/seg_y_min
add wave -noupdate /rasterizer_tb/DUT/seg_y_max
add wave -noupdate /rasterizer_tb/DUT/subpix_x_start
add wave -noupdate /rasterizer_tb/DUT/subpix_y_start
add wave -noupdate /rasterizer_tb/DUT/state_d
add wave -noupdate /rasterizer_tb/DUT/state_q
add wave -noupdate /rasterizer_tb/DUT/pix_ddx_ab
add wave -noupdate /rasterizer_tb/DUT/pix_ddx_bc
add wave -noupdate /rasterizer_tb/DUT/pix_ddx_ca
add wave -noupdate /rasterizer_tb/DUT/pix_ddx_un
add wave -noupdate /rasterizer_tb/DUT/pix_ddx_vn
add wave -noupdate /rasterizer_tb/DUT/pix_ddx_iw
add wave -noupdate /rasterizer_tb/DUT/row_base_ab
add wave -noupdate /rasterizer_tb/DUT/row_base_bc
add wave -noupdate /rasterizer_tb/DUT/row_base_ca
add wave -noupdate /rasterizer_tb/DUT/row_base_un
add wave -noupdate /rasterizer_tb/DUT/row_base_vn
add wave -noupdate /rasterizer_tb/DUT/row_base_iw
add wave -noupdate /rasterizer_tb/DUT/cell_base_ab
add wave -noupdate /rasterizer_tb/DUT/cell_base_bc
add wave -noupdate /rasterizer_tb/DUT/cell_base_ca
add wave -noupdate /rasterizer_tb/DUT/cell_base_un
add wave -noupdate /rasterizer_tb/DUT/cell_base_vn
add wave -noupdate /rasterizer_tb/DUT/cell_base_iw
add wave -noupdate /rasterizer_tb/DUT/cell_ab
add wave -noupdate /rasterizer_tb/DUT/cell_bc
add wave -noupdate /rasterizer_tb/DUT/cell_ca
add wave -noupdate /rasterizer_tb/DUT/cell_un
add wave -noupdate /rasterizer_tb/DUT/cell_vn
add wave -noupdate /rasterizer_tb/DUT/cell_iw
add wave -noupdate /rasterizer_tb/DUT/pix_ab
add wave -noupdate /rasterizer_tb/DUT/pix_bc
add wave -noupdate /rasterizer_tb/DUT/pix_ca
add wave -noupdate /rasterizer_tb/DUT/pix_un
add wave -noupdate /rasterizer_tb/DUT/pix_vn
add wave -noupdate /rasterizer_tb/DUT/pix_iw
add wave -noupdate /rasterizer_tb/DUT/in_triangle
add wave -noupdate /rasterizer_tb/pixblk_mask
add wave -noupdate /rasterizer_tb/pixblk_cy
add wave -noupdate /rasterizer_tb/pixblk_cx
add wave -noupdate /rasterizer_tb/pixblk_valid
add wave -noupdate /rasterizer_tb/pixblk_ready
add wave -noupdate /rasterizer_tb/ddr_h2d
add wave -noupdate /rasterizer_tb/ddr_d2h
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {8856497041 fs} 0}
quietly wave cursor active 1
configure wave -namecolwidth 219
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits fs
update
WaveRestoreZoom {0 fs} {5232296037 fs}
