#!/usr/bin/env python3
"""Build a PPM image directly from accepted simulated DDR color writes."""

import argparse
import csv
from pathlib import Path


CHANNEL_OFFSET = {
    "red": 0,
    "green": 1,
    "blue": 2,
}


def write_channel(pixels, width, height, chunk_x, y, channel, data, mask):
    """Apply one 32-pixel, 256-bit color-channel DDR transaction."""
    if not 0 <= y < height or channel not in CHANNEL_OFFSET:
        return

    channel_offset = CHANNEL_OFFSET[channel]
    for pixel in range(32):
        x = chunk_x * 32 + pixel
        if x < width and ((mask >> pixel) & 1):
            pixels[3 * (y * width + x) + channel_offset] = (
                data >> (8 * pixel)
            ) & 0xff


def convert(log_path, output_path, width, height, fbid):
    pixels = bytearray(width * height * 3)
    clear_writes = 0
    rasterizer_writes = 0

    with log_path.open(newline="") as log_file:
        for line in log_file:
            # Questa prefixes $display output with "# ".  Plain log.csv
            # records have no prefix.
            line = line.strip()
            if line.startswith("# "):
                line = line[2:]
            fields = next(csv.reader([line]))
            if not fields:
                continue

            # Compact clear command emitted to the Questa transcript.
            if fields[0] == "frameclear_cmd" and len(fields) == 8:
                clear_fbid = int(fields[3], 0)
                clear_mode = int(fields[5], 0)
                clear_color = int(fields[7], 16)
                if clear_fbid == fbid and clear_mode == 0:
                    red = (clear_color >> 16) & 0xff
                    green = (clear_color >> 8) & 0xff
                    blue = clear_color & 0xff
                    pixels[:] = bytes((red, green, blue)) * (width * height)
                    clear_writes += 1

            elif fields[0] == "color" and len(fields) in (5, 6):
                if len(fields) == 6:
                    host = int(fields[2], 0)
                    address = int(fields[3], 16)
                    mask = int(fields[4], 16)
                    data = int(fields[5], 16)
                else:
                    host = -1
                    address = int(fields[2], 16)
                    mask = int(fields[3], 16)
                    data = int(fields[4], 16)
                if ((address >> 19) & 0x3) != fbid:
                    continue

                y = (address >> 8) & 0x7ff
                chunk_x = (address >> 2) & 0x3f
                channel_number = address & 0x3
                if channel_number < 3:
                    write_channel(
                        pixels, width, height, chunk_x, y,
                        ("red", "green", "blue")[channel_number],
                        data, mask,
                    )
                    if host == 2:
                        clear_writes += 1
                    else:
                        rasterizer_writes += 1

            # Backward compatibility with the old frameclear log format.
            elif fields[0] == "frameclear" and len(fields) == 6:
                chunk_x = int(fields[2], 0)
                y = int(fields[3], 0)
                channel = fields[4]
                data = int(fields[5], 16)
                write_channel(
                    pixels, width, height, chunk_x, y,
                    channel, data, 0xffffffff,
                )
                clear_writes += 1

            # Raw writer CSV format used during development.
            elif fields[0] == "writer" and len(fields) == 5:
                address = int(fields[2], 16)
                mask = int(fields[3], 16)
                data = int(fields[4], 16)

                # Color layout generated by worker_fifo:
                # {3'h0, fbid[1:0], y[10:0], chunk_x[5:0], channel[1:0]}.
                if (address >> 21) != 0 or ((address >> 19) & 0x3) != fbid:
                    continue

                y = (address >> 8) & 0x7ff
                chunk_x = (address >> 2) & 0x3f
                channel_number = address & 0x3
                if channel_number < 3:
                    write_channel(
                        pixels, width, height, chunk_x, y,
                        ("red", "green", "blue")[channel_number],
                        data, mask,
                    )
                    rasterizer_writes += 1

            # Current human-readable writer line in a Questa transcript:
            # writer,time,address,HEX,mask,HEX,data,HEX
            elif fields[0] == "writer" and len(fields) == 8:
                address = int(fields[3], 16)
                mask = int(fields[5], 16)
                data = int(fields[7], 16)
                if (address >> 21) != 0 or ((address >> 19) & 0x3) != fbid:
                    continue

                y = (address >> 8) & 0x7ff
                chunk_x = (address >> 2) & 0x3f
                channel_number = address & 0x3
                if channel_number < 3:
                    write_channel(
                        pixels, width, height, chunk_x, y,
                        ("red", "green", "blue")[channel_number],
                        data, mask,
                    )
                    rasterizer_writes += 1

    with output_path.open("wb") as ppm_file:
        ppm_file.write(f"P6\n{width} {height}\n255\n".encode("ascii"))
        ppm_file.write(pixels)

    print(f"wrote {output_path} ({width}x{height})")
    print(f"applied {clear_writes} frame-clear writes")
    print(f"applied {rasterizer_writes} rasterizer color writes")
    if rasterizer_writes == 0:
        print("warning: the log contains no completed rasterizer color writes")


def main():
    parser = argparse.ArgumentParser(
        description="Convert rasterizer simulation DDR writes to a binary PPM image."
    )
    parser.add_argument("log", type=Path, help="simulation log.csv")
    parser.add_argument("-o", "--output", type=Path,
                        default=Path("simulation.ppm"))
    parser.add_argument("--width", type=int, default=640)
    parser.add_argument("--height", type=int, default=480)
    parser.add_argument("--fbid", type=int, default=1)
    args = parser.parse_args()

    convert(args.log, args.output, args.width, args.height, args.fbid)


if __name__ == "__main__":
    main()
